[package]
name = "ec-slimloader"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true      # better optimizations
opt-level = "s"

[features]
# Special board support
mimxrt685s-evk = ["imxrt-fcb-rt685evk", "mimxrt685s"]

# FCB support
imxrt-fcb-rt685evk = ["mimxrt685s"]
imxrt-fcb-1spi-a1-nor = ["imxrt-fcb-1spi-nor"]
imxrt-fcb-1spi-b1-nor = ["imxrt-fcb-1spi-nor"]
imxrt-fcb-1spi-nor = ["imxrt"]

# chip variants
mimxrt685s = ["imxrt", "dep:mimxrt685s-pac", "embassy-imxrt/mimxrt685s"]
mimxrt633s = ["imxrt", "embassy-imxrt/mimxrt633s"]

# common imxrt features
imxrt = ["dep:mimxrt600-fcb", "dep:embassy-imxrt"]

# optional debug logging 
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "embassy-executor/defmt",
    "embassy-imxrt/defmt",
    "ec-slimloader-descriptors/defmt",
    "partition-manager/defmt"
]

default = ["imxrt-fcb-rt685evk"]

[dependencies]
# ec-slimloader-descriptors = { git = "https://github.com/wassasin/ec-slimloader-descriptors", branch = "feature/journal-state" }
ec-slimloader-descriptors = { path = "../ec-slimloader-descriptors" }

mimxrt600-fcb = { version = "0.2.0", optional = true }
mimxrt685s-pac = { version = "0.4.0", features = ["rt"], optional = true }
embassy-imxrt = { git = "https://github.com/Wassasin/embassy-imxrt.git", branch = "new-flexspi-driver", default-features = false, optional = true }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", features = [
    "arch-cortex-m",
    "executor-thread",
] }

defmt = { version = "0.3.6", optional = true }
defmt-rtt = { version = "0.4.0", optional = true }

cortex-m = { version = "0.7.7", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.3"
panic-probe = "*"

partition-manager = { git = "https://github.com/OpenDevicePartnership/embedded-services.git", features = ["esa"] }
embassy-sync = { git = "https://github.com/embassy-rs/embassy" }
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.1"

static_cell = "2.1.1"