[workspace]
resolver = "2"
members = [
    "ec-slimloader",
    "ec-slimloader-descriptors"
]
exclude = ["examples/*"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/OpenDevicePartnership/ec-slimloader"

[workspace.lints.rust]
warnings = "deny"

[workspace.dependencies]
defmt = { version = "0.3.6" }
embedded-storage-async = "0.4.1"

[profile.release]
lto = true      # better optimizations
opt-level = "s"