[package]
name = "nonsecure-app"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
cortex-m = { workspace = true, features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt.workspace = true
rtt-target.workspace = true
panic-probe = { version = "1.0", features = ["print-rtt"] }
embassy-imxrt = { workspace = true, features = [
    "time-driver-os-timer",
    "time",
    "mimxrt685s",
    "unstable-pac",
] }
embassy-executor = { workspace = true, features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
] }
embassy-time = "0.5.0"
