[package]
name = "mcxa-security-provisioning"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/OpenDevicePartnership/ec-slimloader"

[dependencies]
defmt = { version = "0.3", optional = true }
defmt-or-log = { version = "0.2.3" }
log = { version = "0.4", optional = true }
cortex-m = "0.7"
embassy-mcxa = { git = "https://github.com/embassy-rs/embassy", default-features = false, features = ["rt"] }

# Re-uses the MCXA lifecycle/IFR types defined in ec-slimloader-mcxa
ec-slimloader-mcxa = { path = "../libs/ec-slimloader-mcxa", default-features = false }

[features]
default = ["log", "mcxa5xx"]
defmt = ["dep:defmt", "defmt-or-log/defmt", "ec-slimloader-mcxa/defmt"]
log = ["dep:log", "defmt-or-log/log", "ec-slimloader-mcxa/log"]
mcxa2xx = ["embassy-mcxa/mcxa2xx", "ec-slimloader-mcxa/mcxa2xx"]
mcxa5xx = ["embassy-mcxa/mcxa5xx", "ec-slimloader-mcxa/mcxa5xx"]
