[package]
name = "example-bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.3"

defmt = "1.0"
defmt-rtt = "1.0"

futures = { version = "0.3.31", default-features = false, features = [
    "async-await",
] }

mimxrt685s-pac = { version = "0.4.0", features = ["rt", "debug"] }

[profile.release]
lto = true
debug = 2
opt-level = "s"
